[workspace]
members = ["dawn", "plugins/common", "plugins/doubler", "plugins/iquery"]
resolver = "2"

[profile.release]
lto = true

[workspace.package]
version = "0.2.0"
authors = ["Jade"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/jumpthewall/DAWN"
homepage = "https://github.com/jumpthewall/DAWN"
keywords = ["dns", "censorship", "wasm", "proxy", "anti-censorship"]
categories = ["network-programming", "wasm"]
